health_checks:
  gitlab_token:
    details: GitLab token invalid (glab auth login needed)
    healthy: false
    last_checked: '2026-01-12T22:36:40.805149'
  kubeconfigs:
    details:
      ephemeral:
        expires: null
        reason: unauthorized
        valid: false
      konflux:
        expires: null
        reason: unauthorized
        valid: false
      prod:
        expires: null
        reason: unauthorized
        valid: false
      stage:
        expires: '2026-01-12T23:49:06.892272'
        remaining_minutes: 72
        valid: true
    healthy: false
    last_checked: '2026-01-12T22:36:38.612354'
  quay_auth:
    details: Quay auth invalid (podman login quay.io needed)
    healthy: false
    last_checked: '2026-01-12T22:36:40.427394'
  vpn:
    details: VPN disconnected (cannot reach internal clusters)
    healthy: false
    last_checked: '2026-01-12T22:36:32.740229'
last_checks:
  kubeconfig_stage_expires: '2026-01-12T23:49:06.892272'
  vpn_last_checked: '2026-01-12T22:36:40.807904'
  vpn_status: disconnected
